Repository nitslaszlo/proba-repo, pull requests merged in 2024-02, with the labels that each got.

#1 fejeselecccö
  Márton Mátyás/recept.txt
Labels: esxgkhjjnbggtr

#2 fejléc létrehozás
  Szabó Bátony/recept.txt
Labels: bug, documentation

#4 fejléc hozzáadása
  Tihanyi Balázs Máté/recept.txt
Labels: bug, documentation

#11 fejléc hozzáadása
  Szalay Gergő/recept.txt
Labels: bug, documentation

#32 lábléc OK
  Nits László/recept.txt
Labels: documentation

#63 Nevsor kitoltve
  névsor.txt
Labels: documentation

#69 névsor kitöltve
  névsor.txt
Labels: documentation

#68 Nevsor kítöltve
  névsor.txt
Labels: dokumentáling

#62 név beírása a névsor.txt be
  névsor.txt
Labels: documentation

#75 Névsor kitöltve
  névsor.txt
Labels: documentation

#66 nevsor kitoltese
  névsor.txt
Labels: documentation

#67 Nevsor kitoltve
  névsor.txt
Labels: documentation

#76 Nevsor kitoltve
  névsor.txt
Labels: documentation

#71 nevsor kitoltese
  névsor.txt
Labels: documentation

#73 nevsor kitoltese
  névsor.txt
Labels: documentation

#70 nevsor kitöltve
  névsor.txt
Labels: documentation

#64 Nevsor kitoltve
  névsor.txt
Labels: documentation

#77 nevsor kitoltve
  névsor.txt
Labels: documentation

#74 Nevsor kitoltve
  névsor.txt
Labels: documentation

#72 névsor kitöltve
  névsor.txt
Labels: documentation
